export const AUTH_CONVERT_TOKEN_REQUEST = 'auth/AUTH_CONVERT_TOKEN_REQUEST'
export const AUTH_CONVERT_TOKEN_SUCCESS = 'auth/AUTH_CONVERT_TOKEN_SUCCESS'
export const AUTH_CONVERT_TOKEN_ERROR = 'auth/AUTH_CONVERT_TOKEN_ERROR'
