export const AUTH_CONVERT_TOKEN_REQUEST = 'auth/AUTH_CONVERT_TOKEN_REQUEST'
export const AUTH_CONVERT_TOKEN_SUCCESS = 'auth/AUTH_CONVERT_TOKEN_SUCCESS'
export const AUTH_CONVERT_TOKEN_ERROR = 'auth/AUTH_CONVERT_TOKEN_ERROR'

export const AUTH_GOOGLE_PROVIDER = 'google-oauth2'
export const AUTH_FACEBOOK_PROVIDER = 'facebook'

export const AUTH_SAVE_CONVERTED_TOKEN = 'auth/SAVE_CONVERTED_TOKEN'
export const AUTH_GET_PERSISTED_TOKEN_REQUEST = 'auth/GET_PERSISTED_TOKEN_REQUEST'
export const AUTH_GET_PERSISTED_TOKEN_SUCCESS = 'auth/GET_PERSISTED_TOKEN_SUCCESS'
export const AUTH_GET_PERSISTED_TOKEN_ERROR = 'auth/GET_PERSISTED_TOKEN_ERROR'
