export const GOOGLE_LOGIN_REQUEST = 'googleLogin/GOOGLE_LOGIN_REQUEST'
export const GOOGLE_LOGIN_SUCCESS = 'googleLogin/GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_ERROR = 'googleLogin/GOOGLE_LOGIN_ERROR'
